# Generated by Django 5.2.16 on 2026-07-29 14:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Profil rasmi"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Hisob balansi",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="O'zingiz haqingizda"),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("uz", "O'zbekcha"), ("ru", "Русский"), ("en", "English")],
                default="uz",
                max_length=5,
                verbose_name="Til",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefon raqami"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("none", "Tanlanmagan"),
                    ("seller", "Sotuvchi"),
                    ("buyer", "Sotib oluvchi"),
                ],
                default="none",
                max_length=10,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "Yorug'"), ("dark", "Qorong'i")],
                default="light",
                max_length=5,
                verbose_name="Mavzu",
            ),
        ),
    ]
