# Generated by Django 5.2.16 on 2026-07-29 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Bloklash sababi"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Bloklangan"),
        ),
        migrations.CreateModel(
            name="AdminMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Sarlavha"
                    ),
                ),
                ("body", models.TextField(verbose_name="Xabar matni")),
                (
                    "is_broadcast",
                    models.BooleanField(default=False, verbose_name="Hammaga"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qabul qiluvchi",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_admin_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yuboruvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrator xabari",
                "verbose_name_plural": "Administrator xabarlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="accounts.adminmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("message", "user")},
            },
        ),
    ]
