# Generated by Django 5.2.16 on 2026-07-30 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_blocked_reason_user_is_blocked_adminmessage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Karta oxirgi 4 raqami"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hisob to'ldirish",
                "verbose_name_plural": "Hisob to'ldirishlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
