# Generated by Django 5.2.16 on 2026-08-02 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_topup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(max_length=25, verbose_name="Karta raqami"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ko'rib chiqilmoqda"),
                            ("approved", "To'landi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Administrator izohi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqti"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pul yechish so'rovi",
                "verbose_name_plural": "Pul yechish so'rovlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
