# Generated by Django 5.2.16 on 2026-08-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_withdrawal"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Telegram chat ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram username"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Ulash kodi"
                    ),
                ),
                ("code_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notifications",
                    models.BooleanField(default=True, verbose_name="Bildirishnomalar"),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram ulanishi",
                "verbose_name_plural": "Telegram ulanishlari",
            },
        ),
    ]
