# Generated by Django 5.2.17 on 2026-08-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_telegramlink"),
        ("payments", "0003_remove_payment_topup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TopUp",
        ),
    ]
