# Generated by Django 5.2.17 on 2026-08-20 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_telegramlink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("payme", "Payme"), ("click", "Click")],
                        max_length=10,
                        verbose_name="To'lov tizimi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Summa"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Yaratildi"),
                            ("waiting", "Kutilmoqda"),
                            ("paid", "To'landi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="created",
                        max_length=10,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Tranzaksiya ID",
                    ),
                ),
                ("created_time", models.BigIntegerField(default=0)),
                ("performed_time", models.BigIntegerField(default=0)),
                ("cancelled_time", models.BigIntegerField(default=0)),
                ("cancel_reason", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topup",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment",
                        to="accounts.topup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "transaction_id"],
                        name="payments_pa_provide_b1dc94_idx",
                    )
                ],
            },
        ),
    ]
