# Generated by Django 5.2.17 on 2026-08-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_conversation_message_wish"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Uy manzili"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="books.book",
                verbose_name="Kitob",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="purchase",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="books.purchase",
            ),
        ),
    ]
