# Generated by Django 5.2.17 on 2026-08-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_address_payment_book_payment_purchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="topup",
        ),
    ]
