# Generated by Django 5.2.16 on 2026-07-29 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="card_last4",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Karta oxirgi 4 raqami"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Karta orqali"),
                    ("pickup", "O'zi olib ketish (naqd)"),
                ],
                default="card",
                max_length=10,
                verbose_name="To'lov usuli",
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoqtirish",
                "verbose_name_plural": "Yoqtirishlar",
                "unique_together": {("book", "user")},
            },
        ),
    ]
