# Generated by Django 5.2.16 on 2026-08-02 17:16

import apps.books.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_purchase_payment_method_purchase_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.books.storage.private_storage,
                upload_to="book_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Kitob fayli (faqat PDF)",
            ),
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(default=1, verbose_name="Joriy sahifa"),
                ),
                (
                    "total_pages",
                    models.PositiveIntegerField(default=0, verbose_name="Jami sahifa"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "O'qish holati",
                "verbose_name_plural": "O'qish holatlari",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "book")},
            },
        ),
    ]
